name: deploy-expiration

# specify when it should be executed
on:
  # whenever we close or merge pull request it's counts as a push to the master branch
  push:
    branches: 
      - master
    # only run whenever something inside expiration directory changes
    paths:
      - 'expiration/**'
jobs:
  build:
    # like docker image, container
    runs-on: ubuntu-latest
    steps:
      # checkout all our code inside of the repo
      - uses: actions/checkout@v2
      # docker is preinstalled on ubuntu
      # creating an image
      - run: cd expiration && docker build -t yarepka/expiration .
      # remember we added secrets
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # push expiration image to the hub
      - run: docker push yarepka/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # use the latest image expiration-depl is the name from the infra/expiration-depl.yaml file
      - run: kubectl rollout restart deployment expiration-depl
      
