name: tests-orders
# determine when we are going to run the workflow (code pushed/pull request created/pull request close/repo is forked)
on:
  # will run whenever pull_request created/updated/reopened
  pull_request:
    # if and only if there are changes to the files in 'orders' 
    # directory then run the job(test)
    paths:
      - 'orders/**'
jobs:
  build:
    # we want to startup some kind of virtual machine which runs ubuntu OS
    runs-on: ubuntu-latest
    #script
    steps:
      # take all the code our our project
      - uses: actions/checkout@v2
      # run all the tests inside of orders service, test:ci runs test one time, not watching like npm run test doing
      - run: cd orders && npm install && npm run test:ci
